name: CURL

on: push

jobs:
  nodejs-api-test:
    runs-on: ubuntu-latest
    steps:  
      - name: Message Working
        run: |
            echo "Estou funcionando"
      - name: Show site
        run :  curl -L https://alexandre-pas-pd.herokuapp.com/
      - name: Find User
        run : |
          curl -i -X GET https://alexandre-pas-dw.herokuapp.com/?page=1&size=10&name=Mike \
        continue-on-error: true
      - name: Get nodejs version
        run: node -v
