name: pull request release
on:
  push
  
jobs:
  strategy:
    runs-on: ubuntu-latest
    steps:
      - name: pull request
        run: curl \
          -X POST \
        -H "Accept: application/vnd.github+json" \
          -H "Authorization: token <TOKEN>" \
             https://api.github.com/repos/GSKUDO/Github-Actions-Stranger-Things/pulls \
            -d '{"title":"PULL REQUEST","body":"pULLS","head":"octocat:release","base":"master"}'
